//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevBuildMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharacterID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> ActorID { get; set; }
    
        public virtual CharacterActor CharacterActor { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
